# MindLoop runtime configuration
# Combines local GPT4All models with OpenAI GPT-4 backend.

runtime:
  cycles: 100          # number of reasoning loops to run
  dry_run: false       # false = actually perform actions
  seed: 42             # fixed random seed for reproducibility

engine: openai
     # default engine family (for local models)

llm:
  gen_defaults:
    temp: 0.6
    top_p: 0.95
    repeat_penalty: 1.1
    max_tokens: 256
    ctx: 4096

models:
  neutral_a: openai:gpt-4.1
  mooded_b: openai:gpt-4.1
  summarizer: openai:gpt-4.1
  coder: openai:gpt-4.1

persona:
  current: Analytical   # selects which persona prompt set to load

prompts: {}             # can point to markdown prompt files if desired

memory:
  faiss_path: ./data/vectors.faiss        # vector store
  sqlite_path: ./data/meta.sqlite3        # metadata store
  recall_k: 8                             # number of nearest neighbors to recall
  alpha: 0.7                              # blending weight between FAISS and FTS recall

safety:
  allowlist_tools: ["ls", "echo", "python3"]  # permitted sandbox commands
  veto_risk: 0.8                              # maximum allowed risk before veto

